apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - image: naresh1985/node-hello-world:32
        name: nodejs-app
        ports:
        - containerPort: 4000
